Added enum example in variables section.
labs42io/clean-code-typescript pull request #25
Opened 2019-05-09 18:28 UTC by lucavictor220

2019-05-21 16:29 UTC, dimadeveatii commented
Please fix above notes.

2019-05-21 16:31 UTC, dimadeveatii requested changes

2019-05-21 16:31 UTC, dimadeveatii commented on README.md
> +  ROMANTIC = 'Romantic',
What is the motivation behind this enum being string-based?  
It is then arguable that it has advantage over bad example with just constants.

Would it be better maybe to use [constant member](https://www.typescriptlang.org/docs/handbook/enums.html#computed-and-constant-members), like:
```ts
enum Genre {
  Romantic,
  Drama,
  ...
}
```

2019-05-30 10:36 UTC, lucavictor220 commented on README.md
> +  ROMANTIC = 'Romantic',
I rethought the intent and motivation of enum.

2019-05-30 10:52 UTC, dimadeveatii requested changes
Much better now!
Please fix only the small typo I suggested in comments.

2019-05-30 10:52 UTC, dimadeveatii commented on README.md
> +        // some logit to be executed
Typo: `logit`

2019-05-30 10:52 UTC, dimadeveatii commented on README.md
> +        // some logit to be executed
Same typo `logit`

2019-05-30 11:59 UTC, lucavictor220 commented on README.md
> +        // some logit to be executed
Done!

2019-05-30 12:01 UTC, dimadeveatii approved these changes

2019-05-30 12:02 UTC, merged